### ISSUE TITLE
Character Sheet is Transparent Unable to See Stats

### ISSUE THREAD

**Issue by alcastilloa** [chrisesharp/foundryvtt-owb#9] opened 2024-07-24 19:21 UTC
Hello,

Wondering if this is the desired behaviour or if I have something going on my end.

Thank you.

**Comment by alcastilloa** [comment] 2024-07-24 19:35
It is on my end. 
Apologies.

**Comment by chrisesharp** [comment] 2024-07-24 20:03
No worries! I love issues that resolve themselves ;-)

**Comment by alcastilloa** [comment] 2024-07-26 17:41
I take it back. Sorry.
Problem is under linux. Could it be the filesystem? 
I took some screenshots, in case they help. Character Sheet is transparent, seems to be tryihg to load the image from two locations. 
<img width="423" alt="ScreenshotOWB-03" src="https://github.com/user-attachments/assets/1c375797-7211-4ccd-9422-032ee89b11d1">
<img width="401" alt="ScreenshotOWB-02" src="https://github.com/user-attachments/assets/903e728d-08a1-48d9-80f4-ced43c9ca508">
<img width="233" alt="ScreenshotOWB-01" src="https://github.com/user-attachments/assets/91183a89-e544-419c-85c8-9ce37f92f7a9">
Under Windows, there is no problem.
Thank you.

**Comment by spossos** [comment] 2024-07-26 17:47
I have seen the same issue on Ubuntu, it is happening on foundry v12. (Seen on .229 and .330). I tested on a clean foundry instance, no other system or world installed.
I hope this gives some help.
Thanks!

**Comment by chrisesharp** [comment] 2024-07-26 18:54
Aha, I see...OK I will investigate. It's interesting that it seems to be affecting multiple images.

**Comment by chrisesharp** [comment] 2024-07-26 18:56
Can you let me know what browsers you are using on Linux?

**Comment by spossos** [comment] 2024-07-26 19:00
The game is hosted on a Linux server, where the issue occurs. When the game is hosted on a Windows machine, no issues are observed. I access the game hosted on Linux from a Windows machine and have tested it using Chrome, Edge, and Firefox; all browsers exhibit the same issue.

**Comment by chrisesharp** [comment] 2024-07-26 19:31
Hmm...then I don't think this is a problem with the system, as I run my games on a Linux image in the cloud, and it all seems to work fine.
<img width="911" alt="Screenshot 2024-07-26 at 20 28 15" src="https://github.com/user-attachments/assets/185c6fd1-052c-4966-8d2d-f2a6fd5fdb8b">

Can I check, are you using any other foundry systems, and do they work? Like OSE, for instance? (I ask because OWB was based off an early version of the OSE code)

**Comment by spossos** [comment] 2024-07-26 19:37
We have other instances with V12, for example one has Alien RPG and it is working fine. Let me please recheck my installation, but yesterday I created a completely new instance and installed only WWII. Thanks, this is actually pretty strange.

**Comment by chrisesharp** [comment] 2024-07-26 19:43
If you can give me a url and login to one with a problem, I'll be happy to have a look.

**Comment by spossos** [comment] 2024-07-26 20:09
Awesome, thanks.
Please check https://littlebigparty.duckdns.org/Test

Go as gamemaster.

Thanks again.

**Comment by chrisesharp** [comment] 2024-07-26 20:23
OK I think the problem is that you have an additional path on your game's root,  /Test. This is breaking it, because usually the root is / so that referring to assets like /systems/owb/... works. But in your setup, it would need to be /Test/systems/owb/...

I've not come across this additional path setup before. How (and why) do you have that there?

**Comment by spossos** [comment] 2024-07-26 20:37
I have a reverse proxy to handle few different instances, for example /Test is used to forward requests to localhost:30011, likewise for other instances.
In foundry config options, there is aparameter to control that path called routePrefix, I only need to set that parameter so Foundry can resolve the actual path.
This is how I have been using it since v11. In v11 there is no issue with this forwarding request.

**Comment by spossos** [comment] 2024-07-27 05:16
I just installed OSE and it works fine

![Screenshot_2024-07-26-22-01-48-69_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/75db347e-5874-40e6-8773-90a0761b429a)

I think you are right and it is related to the routePrefix, few months ago a similar issue happened with a module called NameForge for DnD platform. Maybe this can give you a hint
https://gitlab.com/ElvisPereira/nameforge/-/commit/1656d29b15397becf7ae97221df34106390741f6

Anyway, thanks for looking into this, my friends and I really enjoy the game.

**Comment by chrisesharp** [comment] 2024-07-27 07:42
Ok thank you. I understand the problem. I am just going on holiday for a week now so I'll look into this when I get back.

**Comment by chrisesharp** [comment] 2024-07-27 15:28
OK, as it happens, I got a free hour this afternoon after the beach ;-) 

V1.4.4 should fix this now. Can you verify @spossos @alcastilloa

**Comment by spossos** [comment] 2024-07-27 15:41
Awesome, testing!

**Comment by alcastilloa** [comment] 2024-07-27 15:48
Thank you! Main background is visible. The tabs are still transparent.
![image](https://github.com/user-attachments/assets/36ede591-60b8-47b7-8db0-6853a4f3c03d)

**Comment by chrisesharp** [comment] 2024-07-27 16:13
Argh, I forgot I use some foundry assets, too...v1.4.5 should now fix those (and the health and AC should be fixed, too)

**Comment by alcastilloa** [comment] 2024-07-27 16:30
Chris, enjoy your vacation.Thank you!ÁlvaroOn Jul 27, 2024, at 11:13 AM, Chris Sharp ***@***.***> wrote:﻿
Argh, I forgot I use some foundry assets, too...v1.4.5 should now fix those (and the health and AC should be fixed, too)

**Comment by chrisesharp** [comment] 2024-08-06 11:24
Closing this with release of v1.4.5

**Closed as completed by chrisesharp** 2024-08-06 11:24 UTC
